(part "BM04B-GVHS-TB_LF__SN_"
    (packageRef "BM04BGVHSTBLFSN")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "MP1" (symbPinId 5) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 6) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "BM04B-GVHS-TB(LF)(SN)")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "BM04B-GVHS-TB(LF)(SN)")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bm04b-gvhs-tb-lf-sn/jst-manufacturing?utm_currency=USD&region=europe")
    (property "Description" "CONN HEADER SMD 4POS 1.25MM")
    (property "Datasheet_Link" "http://www.jst-mfg.com/product/pdf/eng/eGVH.pdf")
    (property "symbolName1" "BM04B-GVHS-TB_LF__SN_")
)
