(part "OSTTE040104"
    (packageRef "OSTTE040104")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "On Shore Technology Inc.")
    (property "Manufacturer_Part_Number" "OSTTE040104")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "OSTTE040104")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ostte040104/on-shore-technology?utm_currency=USD&region=nac")
    (property "Description" "TERM BLK 4POS SIDE ENT 3.5MM PCB")
    (property "Datasheet_Link" "https://www.on-shore.com/wp-content/uploads/OSTTEXX0104.pdf")
    (property "symbolName1" "OSTTE040104")
)
