(part "TL3301FF160QG"
    (packageRef "TL3301FF160QG")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "E-Switch")
    (property "Manufacturer_Part_Number" "TL3301FF160QG")
    (property "Mouser_Part_Number" "612-TL3301F")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/E-Switch/TL3301FF160QG?qs=xDsBkp9LkocS2rMBI2Cp5w%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Simulation_Data" "https://configured-product-images.s3.amazonaws.com/Datasheets/TL3301.pdf")
    (property "Description" "TACT, 50mA, 12VDC SPST-NO, Off-(On) Surface Mount")
    (property "Datasheet_Link" "https://configured-product-images.s3.amazonaws.com/2D/specs/TL3301FF160QG.pdf")
    (property "symbolName1" "TL3301FF160QG")
)
