(part "ADS1115LIDGSR"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "ADDR") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ALERT/RDY") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "AIN0") (portType INOUT))
        (port "5" (symbPinId 5) (portName "AIN1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "AIN2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "AIN3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
        (port "9" (symbPinId 9) (portName "SDA") (portType INOUT))
        (port "10" (symbPinId 10) (portName "SCL") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "ADS1115LIDGSR")
    (property "Mouser_Part_Number" "595-ADS1115LIDGSR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/ADS1115LIDGSR?qs=mELouGlnn3cukRGa5QBtug%3D%3D")
    (property "Arrow_Part_Number" "ADS1115LIDGSR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ads1115lidgsr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Analog to Digital Converters - ADC 16-bit, 860-SPS four-channel delta-sigma ADC with PGA, comparator and 1.8-V IC bus voltage support 10-VSSOP -40 to 125")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/ads1115l.pdf?ts=1719994580469&ref_url=https%253A%252F%252Fwww.ti.com%252Fsitesearch%252Fen-us%252Fdocs%252Funiversalsearch.tsp%253FlangPref%253Den-US")
    (property "symbolName1" "ADS1115LIDGSR")
)
