(part "RR0816P-103-D"
    (packageRef "RESC1608X60N")
    (interface
        (port "1" (symbPinId 1) (portName "R1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "R2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "Susumu")
    (property "Manufacturer_Part_Number" "RR0816P-103-D")
    (property "Mouser_Part_Number" "754-RR0816P-103D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Susumu/RR0816P-103-D?qs=nCAm%252BcMdy9zJFUifGf2vtQ%3D%3D")
    (property "Arrow_Part_Number" "RR0816P-103-D")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/rr0816p-103-d/susumu")
    (property "Description" "RESISTOR, 0603 10 KOhm +/- 0.5% 0.0625 W")
    (property "Datasheet_Link" "http://componentsearchengine.com/Datasheets/1/RR0816P-103-D.pdf")
    (property "symbolName1" "RR0816P-103-D")
)
