(part "CL10A106KP8NNNC"
    (packageRef "CAPC1608X90N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "SAMSUNG")
    (property "Manufacturer_Part_Number" "CL10A106KP8NNNC")
    (property "Mouser_Part_Number" "187-CL10A106KP8NNNC")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Samsung-Electro-Mechanics/CL10A106KP8NNNC?qs=X6jEic%2FHinAlyfRHj7fKwg%3D%3D")
    (property "Arrow_Part_Number" "CL10A106KP8NNNC")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/cl10a106kp8nnnc/samsung-electro-mechanics?utm_currency=USD&region=europe")
    (property "Description" "10F +/-10% 10V Ceramic Capacitor X5R 0603 (1608 Metric)")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-DGA10/2415998.pdf")
    (property "symbolName1" "CL10A106KP8NNNC")
)
