(part "TJA1050T_CM_118"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "TXD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VCC") (portType INOUT))
        (port "4" (symbPinId 4) (portName "RXD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VREF") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CANL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CANH") (portType INOUT))
        (port "8" (symbPinId 8) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "NXP")
    (property "Manufacturer_Part_Number" "TJA1050T/CM,118")
    (property "Mouser_Part_Number" "771-TJA1050T/CM118")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/NXP-Semiconductors/TJA1050T-CM118?qs=5XOdhvmYM0NFFspw0VP5sA%3D%3D")
    (property "Arrow_Part_Number" "TJA1050T/CM,118")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tja1050tcm118/nxp-semiconductors?utm_currency=USD&region=nac")
    (property "Description" "NXP - TJA1050T/CM,118 - CAN TRANSCEIVER, 1TX/RX, SOIC-8")
    (property "Datasheet_Link" "http://www.nxp.com/docs/en/data-sheet/TJA1050.pdf")
    (property "symbolName1" "TJA1050T_CM_118")
)
