(part "D5V0F1U2LP-7B"
    (packageRef "D5V0F1U2LP7B")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "D5V0F1U2LP-7B")
    (property "Mouser_Part_Number" "621-D5V0F1U2LP7B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/D5V0F1U2LP-7B?qs=vkMqrgFpRajm13%252B24IP7Kw%3D%3D")
    (property "Arrow_Part_Number" "D5V0F1U2LP-7B")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/d5v0f1u2lp-7b/diodes-incorporated?utm_currency=USD&region=nac")
    (property "Description" "12V Clamp 1.5A (8/20s) Ipp Tvs Diode Surface Mount X1-DFN1006-2")
    (property "Datasheet_Link" "https://www.diodes.com/assets/Datasheets/D5V0F1U2LP.pdf")
    (property "symbolName1" "D5V0F1U2LP-7B")
)
