(part "RCLAMP3521ZATFT"
    (packageRef "RCLAMP3521ZATFT")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "SEMTECH")
    (property "Manufacturer_Part_Number" "RCLAMP3521ZATFT")
    (property "Mouser_Part_Number" "947-RCLAMP3521ZATFT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Semtech/RCLAMP3521ZATFT?qs=5aG0NVq1C4x6ouY7l2JqqA%3D%3D")
    (property "Arrow_Part_Number" "RCLAMP3521ZATFT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/rclamp3521zatft/semtech?utm_currency=USD&region=nac")
    (property "Description" "TVS DIODE 3.5VWM 5V SLP0603P2X3F5V (Typ) Clamp 6A Ipp Tvs Diode Surface Mount SLP0603P2X3F")
    (property "Datasheet_Link" "https://semtech.my.salesforce.com/sfc/p/E0000000JelG/a/2R000000HTFj/RtolUnnSswHAEeYsM7sjR2dAo9HQRz.z1PGO8KUTcfs")
    (property "symbolName1" "RCLAMP3521ZATFT")
)
