(part "ERA2AEB470X"
    (packageRef "ERA2AED122X")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "ERA2AEB470X")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Panasonic ERA Series Thin Film Surface Mount Resistor 0402 Case 47 +/-0.1% 0.063W +/-25ppm/C")
    (property "Datasheet_Link" "http://industrial.panasonic.com/cdbs/www-data/pdf/RDM0000/AOA0000C307.pdf")
    (property "symbolName1" "ERA2AEB470X")
)
