(part "LSM6DSV16BXTR"
    (packageRef "LSM6DSV16BXTR")
    (interface
        (port "1" (symbPinId 1) (portName "SDO/SA0") (portType INOUT))
        (port "2" (symbPinId 2) (portName "TDMOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "BCLK") (portType INOUT))
        (port "4" (symbPinId 4) (portName "INT1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VDD_IO") (portType INOUT))
        (port "6" (symbPinId 6) (portName "AH1/QVAR1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
        (port "9" (symbPinId 9) (portName "AH2/QVAR2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "INT2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "WCLK") (portType INOUT))
        (port "12" (symbPinId 12) (portName "CS") (portType INOUT))
        (port "13" (symbPinId 13) (portName "SCL") (portType INOUT))
        (port "14" (symbPinId 14) (portName "SDA") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "LSM6DSV16BXTR")
    (property "Mouser_Part_Number" "511-LSM6DSV16BXTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/LSM6DSV16BXTR?qs=vvQtp7zwQdMXKB4RqH7GHQ%3D%3D")
    (property "Arrow_Part_Number" "LSM6DSV16BXTR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/lsm6dsv16bxtr/stmicroelectronics?utm_currency=USD&region=nac")
    (property "Description" "6-axis IMU (inertial measurement unit) with embedded sensor fusion, AI, Qvar and hearable features for TWS")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/lsm6dsv16bx.pdf")
    (property "symbolName1" "LSM6DSV16BXTR")
)
