(part "7914G-1-032E"
    (packageRef "7914G1032E")
    (interface
        (port "A1" (symbPinId 1) (portName "COM_1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "NO_1") (portType INOUT))
        (port "B1" (symbPinId 3) (portName "COM_2") (portType INOUT))
        (port "B2" (symbPinId 4) (portName "NO_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "7914G-1-032E")
    (property "Mouser_Part_Number" "652-7914G-1-032E")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/7914G-1-032E?qs=b0Ldvwy66%2F%2FgyAckl4Lgjg%3D%3D")
    (property "Arrow_Part_Number" "7914G-1-032E")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/7914g-1-032e/bourns?region=nac")
    (property "Description" "Tactile Switches 4mm KEY SWITCH SMD Gull Wing")
    (property "Datasheet_Link" "https://www.bourns.com/docs/Product-Datasheets/7914.pdf")
    (property "symbolName1" "7914G-1-032E")
)
