(part "C0603C103F3GECTU"
    (packageRef "CAPC1608X87N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "YAGEO")
    (property "Manufacturer_Part_Number" "C0603C103F3GECTU")
    (property "Mouser_Part_Number" "80-C0603C103F3GEC")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KEMET/C0603C103F3GECTU?qs=Mv7BduZupUjWMY5EogEjUg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "ESD SMD Comm C0G, Ceramic, 0.01 uF, 1%, 25 VDC, 62.5 VDC, 125C, -55C, C0G, SMD, MLCC, Temperature Stable, Electro Static Discharge, Class I, 0.1 % , 100 GOhms, 3.7 mg, 0603, 1.6mm, 0.8mm, 0.8mm, 0.7mm, 0.35mm, 4000, 78  Weeks, 120")
    (property "Datasheet_Link" "https://content.kemet.com/datasheets/KEM_C1003_C0G_SMD.pdf")
    (property "symbolName1" "C0603C103F3GECTU")
)
