(part "ESP32-S3-MINI-1-N8"
    (packageRef "ESP32S3MINI1N8")
    (interface
        (port "1" (symbPinId 1) (portName "GND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3V3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IO0") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IO1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IO2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "IO3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "IO4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "IO5") (portType INOUT))
        (port "10" (symbPinId 10) (portName "IO6") (portType INOUT))
        (port "11" (symbPinId 11) (portName "IO7") (portType INOUT))
        (port "12" (symbPinId 12) (portName "IO8") (portType INOUT))
        (port "13" (symbPinId 13) (portName "IO9") (portType INOUT))
        (port "14" (symbPinId 14) (portName "IO10") (portType INOUT))
        (port "15" (symbPinId 15) (portName "IO11") (portType INOUT))
        (port "16" (symbPinId 16) (portName "IO12") (portType INOUT))
        (port "17" (symbPinId 17) (portName "IO13") (portType INOUT))
        (port "18" (symbPinId 18) (portName "IO14") (portType INOUT))
        (port "19" (symbPinId 19) (portName "IO15") (portType INOUT))
        (port "20" (symbPinId 20) (portName "IO16") (portType INOUT))
        (port "21" (symbPinId 21) (portName "IO17") (portType INOUT))
        (port "22" (symbPinId 22) (portName "IO18") (portType INOUT))
        (port "23" (symbPinId 23) (portName "IO19") (portType INOUT))
        (port "24" (symbPinId 24) (portName "IO20") (portType INOUT))
        (port "25" (symbPinId 25) (portName "IO21") (portType INOUT))
        (port "26" (symbPinId 26) (portName "IO26") (portType INOUT))
        (port "27" (symbPinId 27) (portName "IO47") (portType INOUT))
        (port "28" (symbPinId 28) (portName "IO33") (portType INOUT))
        (port "29" (symbPinId 29) (portName "IO34") (portType INOUT))
        (port "30" (symbPinId 30) (portName "IO48") (portType INOUT))
        (port "31" (symbPinId 31) (portName "IO35") (portType INOUT))
        (port "32" (symbPinId 32) (portName "IO36") (portType INOUT))
        (port "33" (symbPinId 33) (portName "IO37") (portType INOUT))
        (port "34" (symbPinId 34) (portName "IO38") (portType INOUT))
        (port "35" (symbPinId 35) (portName "IO39") (portType INOUT))
        (port "36" (symbPinId 36) (portName "IO40") (portType INOUT))
        (port "37" (symbPinId 37) (portName "IO41") (portType INOUT))
        (port "38" (symbPinId 38) (portName "IO42") (portType INOUT))
        (port "39" (symbPinId 39) (portName "TXD0") (portType INOUT))
        (port "40" (symbPinId 40) (portName "RXD0") (portType INOUT))
        (port "41" (symbPinId 41) (portName "IO45") (portType INOUT))
        (port "42" (symbPinId 42) (portName "GND_3") (portType INOUT))
        (port "43" (symbPinId 43) (portName "GND_4") (portType INOUT))
        (port "44" (symbPinId 44) (portName "IO46") (portType INOUT))
        (port "45" (symbPinId 45) (portName "EN") (portType INOUT))
        (port "46" (symbPinId 46) (portName "GND_5") (portType INOUT))
        (port "47" (symbPinId 47) (portName "GND_6") (portType INOUT))
        (port "48" (symbPinId 48) (portName "GND_7") (portType INOUT))
        (port "49" (symbPinId 49) (portName "GND_8") (portType INOUT))
        (port "50" (symbPinId 50) (portName "GND_9") (portType INOUT))
        (port "51" (symbPinId 51) (portName "GND_10") (portType INOUT))
        (port "52" (symbPinId 52) (portName "GND_11") (portType INOUT))
        (port "53" (symbPinId 53) (portName "GND_12") (portType INOUT))
        (port "54" (symbPinId 54) (portName "GND_13") (portType INOUT))
        (port "55" (symbPinId 55) (portName "GND_14") (portType INOUT))
        (port "56" (symbPinId 56) (portName "GND_15") (portType INOUT))
        (port "57" (symbPinId 57) (portName "GND_16") (portType INOUT))
        (port "58" (symbPinId 58) (portName "GND_17") (portType INOUT))
        (port "59" (symbPinId 59) (portName "GND_18") (portType INOUT))
        (port "60" (symbPinId 60) (portName "GND_19") (portType INOUT))
        (port "61" (symbPinId 61) (portName "GND_20") (portType INOUT))
        (port "62" (symbPinId 62) (portName "GND_21") (portType INOUT))
        (port "63" (symbPinId 63) (portName "GND_22") (portType INOUT))
        (port "64" (symbPinId 64) (portName "GND_23") (portType INOUT))
        (port "65" (symbPinId 65) (portName "GND_24") (portType INOUT))
        (port "66" (symbPinId 66) (portName "GND_25") (portType INOUT))
        (port "67" (symbPinId 67) (portName "GND_26") (portType INOUT))
        (port "68" (symbPinId 68) (portName "GND_27") (portType INOUT))
        (port "69" (symbPinId 69) (portName "GND_28") (portType INOUT))
        (port "70" (symbPinId 70) (portName "GND_29") (portType INOUT))
        (port "71" (symbPinId 71) (portName "GND_30") (portType INOUT))
        (port "72" (symbPinId 72) (portName "GND_31") (portType INOUT))
        (port "73" (symbPinId 73) (portName "GND_32") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Espressif Systems")
    (property "Manufacturer_Part_Number" "ESP32-S3-MINI-1-N8")
    (property "Mouser_Part_Number" "356-ESP32-S3-MINI1N8")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Espressif-Systems/ESP32-S3-MINI-1-N8?qs=XAiT9M5g4x82rl6F%2FIYUQg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "WiFi Development Tools - 802.11 [Engineering Samples] SMD Module, ESP32-S3FN8, 8 MB SPI Flash, PCB Antenna")
    (property "Datasheet_Link" "https://www.espressif.com/sites/default/files/documentation/esp32-s3-mini-1_mini-1u_datasheet_en.pdf")
    (property "symbolName1" "ESP32-S3-MINI-1-N8")
)
