(part "AMS1117-3_3"
    (packageRef "SOT229P700X180-4N")
    (interface
        (port "1" (symbPinId 1) (portName "GND/ADJ") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Advanced")
    (property "Manufacturer_Part_Number" "AMS1117-3.3")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Descriptions of ams AMS1117-3.3 provided by its distributors.")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-28/DSA-550594.pdf")
    (property "symbolName1" "AMS1117-3_3")
)
