(part "SN74LVC1T45DCKR"
    (packageRef "SOT65P210X110-6N")
    (interface
        (port "1" (symbPinId 1) (portName "VCCA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "B") (portType INOUT))
        (port "5" (symbPinId 5) (portName "DIR") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VCCB") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "SN74LVC1T45DCKR")
    (property "Mouser_Part_Number" "595-SN74LVC1T45DCKR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/SN74LVC1T45DCKR?qs=gb35HGp1gQLgs5JLyVnp7g%3D%3D")
    (property "Arrow_Part_Number" "SN74LVC1T45DCKR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/sn74lvc1t45dckr/texas-instruments?region=nac")
    (property "Description" "Texas Instruments SN74LVC1T45DCKR, Bus Transceiver Non-Inverting LVTTL, 1.65  5.5 V, 6-Pin SC-70")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/sn74lvc1t45")
    (property "symbolName1" "SN74LVC1T45DCKR")
)
