(part "GRM31CR61A107MEA8L"
    (packageRef "GRM31x")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "GRM31CR61A107MEA8L")
    (property "Mouser_Part_Number" "81-GRM31CR61A107MA8L")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/GRM31CR61A107MEA8L?qs=hd1VzrDQEGidurXiDTJOCg%3D%3D")
    (property "Arrow_Part_Number" "GRM31CR61A107MEA8L")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/grm31cr61a107mea8l/murata-manufacturing?utm_currency=USD&region=europe")
    (property "Description" "MLCC, 1206")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM31CR61A107MEA8-01A.pdf")
    (property "symbolName1" "GRM31CR61A107MEA8L")
)
