M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-02-27T00:56:05-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-27T00:56:05-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X30.95Y-71.25
X31.9Y-34.95
M30
