(part "ERA-2AEB101X"
    (packageRef "ERA2AED122X")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "ERA-2AEB101X")
    (property "Mouser_Part_Number" "667-ERA-2AEB101X")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/ERA-2AEB101X?qs=YFwoyZoVY0i6%2FzAzf7zwiw%3D%3D")
    (property "Arrow_Part_Number" "ERA-2AEB101X")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/era-2aeb101x/panasonic?utm_currency=USD&region=europe")
    (property "Description" "PANASONIC ELECTRONIC COMPONENTS - ERA-2AEB101X - METAL FILM RESISTOR, 100OHM, 63mW,  0.1%, FULL REEL")
    (property "Datasheet_Link" "http://industrial.panasonic.com/cdbs/www-data/pdf/RDM0000/AOA0000C307.pdf")
    (property "symbolName1" "ERA-2AEB101X")
)
