M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-03-01T10:35:37-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-01T10:35:37-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X30.95Y-71.25
X32.09Y-36.1
M30
